version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python UnitTesting.py
  post_build:
    commands:
      - aws cloudformation package --template-file cf_template.yml --s3-bucket ${ARTIFACT_BUCKET} --output-template-file outputTemplate.yml

artifacts:
  type: zip
  files:
    - cf_template.yml
    - outputTemplate.yml
    - Testing_compatible_code.py
    - UnitTesting.py
    - requirements.txt